name: GogaDent

color:
    primary: 2C3E50
    secondary: 18BC9C
    
contact:
    office:
        fb: http://facebook.com/IQDent
        gplus: https://plus.google.com/+IqdentRo
        twitter: 
        tel: 0766 748 971
        address: 
            street: Bulevardul Octavian Goga Nr 21
            house: Bl M103, Sc 2, Ap 37, Interfon 37
            city: Sector 3, Bucure»ôti
            
    one: 
        name: Dr. Irina Alexandru
        prefix: irina-
        tel: 0766 748 971
        img: img/team/irina.jpg
        fb: https://www.facebook.com/dririnaalexandru
        msg: https://www.facebook.com/messages/dririnaalexandru
    two: 
        name: Dr. Petronela Poenaru
        prefix: petro-
        tel: 0721 502 570
        img: img/team/petro.jpg
        fb:
        
discounts:
    expiry: 1 Septembrie 2017


gems:
  - jekyll-sitemap